[sqlserver]
table_name1=select TABLE_NAME from INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME not like 'syncobj%' and TABLE_NAME not like 'MS%'  and TABLE_TYPE = 'BASE TABLE' and TABLE_SCHEMA = 'dbo'
table_name=select name from sys.objects where is_ms_shipped!=1 and type_desc='USER_TABLE' and schema_id=SCHEMA_ID('dbo')
col=select ORDINAL_POSITION,COLUMN_NAME,data_type,CHARACTER_OCTET_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,DATETIME_PRECISION,IS_NULLABLE from INFORMATION_SCHEMA.COLUMNS where TABLE_SCHEMA = 'dbo' and TABLE_NAME='{tbname}'
cons_pqc= SELECT  p.Table_name,p.COLUMN_NAME,CONSTRAINT_NAME,p.COLUMN_DEFAULT FROM   INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE left join INFORMATION_SCHEMA.COLUMNS as p on p.COLUMN_NAME=INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.COLUMN_NAME and p.TABLE_NAME =INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE.TABLE_NAME WHERE   CONSTRAINT_SCHEMA = 'dbo'  and p.TABLE_NAME='test_cons5'
index=select indname=a.name ,tablename=c.name ,col_name=d.name ,索引字段位置=d.colid  FROM  sysindexes   a JOIN   sysindexkeys   b   ON   a.id=b.id   AND   a.indid=b.indid JOIN   sysobjects   c   ON   b.id=c.id  JOIN   syscolumns   d   ON   b.id=d.id   AND   b.colid=d.colid WHERE   a.indid   NOT IN(0,255) AND   c.name='test_cons5'

sync=select name,schema_id,type_desc,base_object_name from sys.synonyms
row=select * from
[oracle]
table_name=SELECT table_name FROM all_tables where owner='{schema}'
col=SELECT column_id,column_name,data_type,data_length,data_precision,data_scale,data_scale,nullable FROM all_tab_columns t WHERE t.OWNER='{schema}' AND t.TABLE_NAME=
cons=SELECT CONSTRAINT_NAME, SEARCH_CONDITION FROM all_CONSTRAINTS WHERE TABLE_NAME = '{tbname}' AND CONSTRAINT_TYPE = 'C'
row=select {columns} from {tbname} order by 1 asc
ob_cons=select to_char(DBMS_METADATA.GET_DDL('INDEX',index_name,'{schema}')) from (SELECT index_name FROM all_INDEXES u where TABLE_OWNER='{schema}'  and TABLE_NAME='{tbname}')
[postgre]
table_name=
col=select ORDINAL_POSITION,COLUMN_NAME,data_type,CHARACTER_OCTET_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,DATETIME_PRECISION,IS_NULLABgreLE from INFORMATION_SCHEMA.COLUMNS where Table_schema='{schema}' and TABLE_NAME=
cons=SELECT * FROM   INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE WHERE  CONSTRAINT_SCHEMA = '{schema}' and TABLE_NAME ='{tbname}'
row=select * from
def=select column_name,column_default from INFORMATION_SCHEMA.columns where TABLE_NAME = '{tbname}' and table_schema='{schema}'

[mysql]
table_name=select table_name from information_schema.tables where table_schema='{schema}' and table_type='BASE TABLE'
col=select ORDINAL_POSITION,COLUMN_NAME,data_type,CHARACTER_OCTET_LENGTH,NUMERIC_PRECISION,NUMERIC_SCALE,DATETIME_PRECISION,IS_NULLABLE from INFORMATION_SCHEMA.COLUMNS where TABLE_SCHEMA = '{schema}' and TABLE_NAME=
cons=
row=select * from

[clickhouse]
table_name=show tables
col=SELECT position,name,type,character_octet_length,numeric_precision,numeric_scale,datetime_precision,type FROM system.columns where database = '{dbname}' and table = '{tbname}' order by position
cosn=show create {tbname}

[dm]
table_name=SELECT TABLE_NAME FROM all_tables WHERE owner='{schema}'
col=SELECT CAST(COLUMN_ID AS int),COLUMN_NAME,DATA_TYPE,CAST(DATA_LENGTH AS int),CAST(DATA_PRECISION AS int),CAST(DATA_SCALE AS int),CAST(DATA_SCALE AS int),NULLABLE from all_tab_columns where owner='{schema}' and Table_Name='{tbname}';
#def=select column_name,data_default from all_tab_columns  where owner='{schema}' and Table_Name='{tbname}';
cons=SELECT DBMS_METADATA.GET_DDL('TABLE','{tbname}','{schema}')
select=select * from {schema}."{tbname}" order by 1 asc
def=select atc.COLUMN_name,data_default,dic.index_name,dic.index_type,dic.uniqueness from all_tab_columns atc LEFT JOIN (SELECT dic.column_name,dic.index_name,ai.INDEX_type,ai.uniqueness FROM dba_ind_columns dic JOIN ALL_INDEXES ai ON dic.index_name=ai.index_name WHERE dic.index_owner='{schema}' and dic.table_name='{tbname}')AS dic ON atc.column_name = dic.column_name WHERE atc.owner = '{schema}' AND atc.table_name = '{tbname}'

[hive]
table_name=select  cast(table_name as string) from system.tables_v where database_name = '{dbname}';
col=select column_id+1,cast(column_name as string),column_type,column_length,column_scale,column_scale,column_scale,cast(nullable as string),cast(table_name as string)
 from system.columns_v where database_name = '{dbname}' and table_name='{tbname}' order by column_id;
row=select * from {dbname}.{tbname} order by {ob} asc;
pri=select cast(table_name as string),cast(bucket_column as string) from system.buckets_v where database_name='{dbname}' order by table_name;
col_02=select cast(column_name as string) from  system.columns_v where database_name='{dbname}' and table_name='{tbname}' order by column_id;

[db2]
col=select colno,colname,typename,LENGTH,LENGTH,SCALE,SCALE,NULLS,tabname from syscat.columns where tabschema='{schema}' and tabname='{tbname}' order by colno;
cons=SELECT indname,colnames,uniquerule,colcount FROM syscat.indexes WHERE TABNAME ='{tbname}' and tabschema='{schema}' UNION SELECT constname,CAST(text AS varchar(300)),type,1 FROM syscat.checks where owner='{schema}' and TABNAME ='{tbname}'
def=select colname,default from syscat.columns where tabschema='{schema}' AND tabname='{tbname}' order by colno
uni=SELECT constname,colname,colseq FROM SYScat.keycoluse WHERE tabschema='{schema}' AND tabname='{tbname}'
indx=select NAME,TBNAME,COLNAMES,UNIQUERULE,INDEXTYPE from sysibm.sysindexes where tbname='{tbname}'
[pri]
mssql=SELECT table_name FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_CATALOG='{dbname}' and CONSTRAINT_TYPE = 'PRIMARY KEY' and constraint_schema='dbo'
