##mssql默schema为dbo
#-*- coding:utf-8 -*-
#---------------sqlserver-------------#
[mssql#]
host=192.168.62.130
port=1433
username=sa
password=root
databasename=info
type=sqlserver
[130.eight]
host=192.168.62.130
port=1433
username=sa
password=root
databasename=eight
type=sqlserver
[mssql##]#9.0 117
host=172.20.72.117
port=1433
username=sa
password=Info1234
databasename=doris
type=sqlserver
[mssql_chenqq]#9.0 117
host=172.16.0.88
port=1433
username=sa
password=147258369
databasename=testldfsrcdb
type=sqlserver
#mssql 192.168.62.218
[mssql###*]#131.32 ssms2016 develop ,2016 sp2 192.168.23.218
host=10.1.131.32
port=1433
username=sa
password=root
databasename=noshare
type=sqlserver
[sqlserver01]#128 windows server 2019 sqlserver 2014 enterprise
host=10.1.131.38
port=1433
username=sa
password=Info1234!
databasename=agdb
type=sqlserver
[sqlserver23.2]#128 windows server 2019 sqlserver 2014 enterprise
host=192.168.23.2
port=1433
username=sa
password=Info1234
databasename=zh105
type=sqlserver

[hive]#ArgoDB
host=cdh1
port=10000
username=
password=
databasename=default
type=hive

[mssql###]#winserver 2012 ssms2012 Always on --proxy
host=192.168.23.41
port=1433
username=sa
password=Info1234
databasename=gold
type=sqlserver
[mssql#win10]#win10 sqlserver 2019 develop
host=10.1.131.31
port=1433
username=sa
password=Info1234
databasename=test
type=sqlserver
## 目标数据库(sqlserver)
#-----------------mysql------------#
[mysql]#10.1.131.39##39常驻38djnago
host=122.51.173.138
port=3306
username=root
password=Info1234!
databasename=cs_remote
type=mysql

[mysql#goldenDB]#goldenDB
host=10.1.123.31
port=8880
username=dbo
password=root
databasename=dbo
type=mysql
[doris]#doris
host=10.1.111.181
port=19030
username=whb
password=123456
databasename=dbo
type=mysql
[doris2]#doris
host=10.1.131.122
port=9030
username=dbo
password=root
databasename=dbo
type=mysql
[mysql_argo]#8.0
host=192.168.62.116
port=3306
username=root
password=Info1234!
databasename=dbo
type=mysql
#mysql -uy1 -pInfo1234___ -P15002 -h172.20.74.211 -A
[mysql#]#tidb
host=172.20.75.11
port=4000
username=root
password=123456
databasename=dbo
type=mysql
[mysql##]#5.7
host=10.1.111.21
port=3306
username=root
password=Info1234!
databasename=dbo
type=mysql

[tdsql]
host=172.20.74.211
port=15002
username=y1
password=Info1234___
databasename=dbo
type=mysql

[tdsql_pg]
host=172.20.74.211
port=15002
username=y1
password=Info1234___
databasename=dbo
type=postgre
#-----------oracle------------#
[oracle]#10.1.131.39
host=10.1.131.39
port=1521
username=DBO
password=root
databasename=ORCLPDB1
schema=DBO
type=oracle
[oboracle]#ob ora3.2.4
host=10.1.126.102
port=2881
username=root
password=Info2Soft@2023#
databasename=sys
type=ob_oracle
#cluster=obcluster

[oracle#shizc]#shizc/19c/dbo low
host=172.20.72.77
port=1521
username=DBO_TEST
password=root
databasename=pdb02
type=oracle

[oracle_11g]
host=192.168.23.181
port=1521
username=dbo
password=root
databasename=orcl
type=oracle

[postgre]#liucj
host=10.1.131.39
port=54321
username=root
password=root
databasename=dbo
schema=dbo
type=postgre

[postgre_liyz]
host=172.20.75.89
port=5432
username=liyz89
password=123456
databasename=postgres
schema=dbo
type=postgre

[postgre##]#liht@tbase psql -U tbase -d postgres -h 172.20.66.183 -p 11006
host=172.20.66.183
port=11006
username=dbo
password=root
databasename=perf
schema=dbo
type=postgre

[postgre_wanglq]#_aliyun
host=172.20.73.230
port=5432
username=lky
password=root
databasename=postgres
schema=pg11
type=postgre

[polar]#_aliyun
host=172.20.72.52
port=5432
username=dbo
password=root
databasename=dbo
schema=public
type=postgre
[postgre_GP]#liuc@greenplum
host=10.1.122.40
port=5432
username=gpadmin
password=gpadmin
databasename=postgres
schema=dml
type=postgre
[lightdb]
host=172.20.66.179
port=5432
username=lky
password=root
databasename=dbo_pg
schema=dbo
type=postgre
#---------------------------#
[opengauss]
host=172.20.73.178
port=36000
username=lky
password=sanitater123!
databasename=l_utf
schema=dbo
type=postgre

[opengauss_gbk]
host=172.20.73.178
port=36000
username=lky
password=sanitater123!
databasename=l_gbk
schema=dbo
type=postgre
[dws]
host=172.20.72.188
port=25308
username=lky
password=Info1234!
databasename=l_utf
schema=dbo
type=postgre
#-----------DB2----------------#
[db2_97]#V9.7/V9.7 4-dpf
host=10.1.131.52
port=60001
username=db2inst1
password=root
databasename=test
schema=db2inst1
dpf=1
type=db2

[db2_dpf105]#V10.5/DTT
host=10.1.131.56
port=60000
username=db2inst1
password=root
databasename=test_utf
schema=db2inst1
dpf=1
type=db2
[db2_as400]#V10.5/as400//as400需要手动建立srcpf、pf类型mbr文件
host=185.113.5.134
port=446
username=JXGENIUS
password=Info1234
databasename=jxgenius1
schema=jxgenius1
type=db2_as400
dpf=1
srcpf=srct
mbr=pydds
[db2]#V10.5/DTT
host=10.1.28.174
port=50658
username=db2inst1
password=123456
databasename=test1
schema=db2inst1
type=db2
dpf=1
#----------oceanbase-------------#
#-----ob:user:用户@租户
[ob_oracle]#obora 4.2
host=10.1.113.60
port=2881
username=sys@oracle_utf8
password=OceanBase4321%%
databasename=TPCC
type=ob_oracle
[ob_mysql]#obora 4.2
host=10.1.113.60
port=2881
username=root@mysql_uft8
password=OceanBase4321%%
databasename=dbo
type=ob_mysql
#----------clickhouse-----------------#
[clickhouse]
host=172.20.72.116
port=9000
username=dbo
password=root
databasename=DBO
type=clickhouse
#------------DM version:8--------------#
[dm]#104
host=10.1.111.104
port=5236
username=dbo
password=dameng123
databasename=DBO
type=dm
[elastic]
host=172.20.72.116
port=9200
username=SYSDBA
password=SYSDBA
databasename=dbo
schema=dbo
## ---------Hive-------------#
##Hyperbase - ssh长连接+kerberos
[hyperbase]#jypye-TDH 172.20.72.196~198 纯hbase无phoenix/hive/thrift
host=172.20.72.196
port=8020
zk_host=172.20.72.196
zk_port=2181
ker=1
username=root
password=Info@1234
namespace=dbo
kpath=D://Info/etc//tdhall.keytab
principle=hbase/tdh1@TDH
exec_threads=2
recv_threads=2
type=hbase
[hyperbase184]#hbase 10.1.111.184 root/Info1114! 无认证
host=10.1.111.184
port=9000
zk_host=10.1.111.184
zk_port=2181
ker=0
username=root
password=Info@1234
namespace=dbo
kpath=D://Info/etc//tdhall.keytab
principle=hbase/tdh1@TDH
exec_threads=2
recv_threads=2
type=hbase
[case]
## ---------用例包case根目录-------------#
case_dir=D:\Info\case_resource\
#------------queue、kafka 队列--------------#
dir=r'D:\Info\iastream-queue-7.1.74.23122113\stream-queue\iastream-queue\bin\log\iaqueue'
compare_file=r'D:\Info\log\log1.txt'


#----------------NoSql----------#
[mongo]#v4.2.6
host=10.1.111.225
port=27001
databasename=dbo
schema=dbo
type=mongo
[mongo_a]#v3.6
host=10.1.131.34
port=27001
databasename=dbo
schema=dbo
type=mongo
#hdfs现需手动下载所有表到本地路径 local_dir下再做比较
[hdfs]
host=10.1.123.11
port=9870
schema=dbo_test
user=root
#默认路径为/{schema},特殊情况写明具体路径
dir=/dbo_test
local_dir=D:\Info\hdfs\
kerberos=yes

[400_type]
type={"smallint": "5B","integer": "9B","int":"9B","bigint": "10B","decimal": "P","dec": "P","real": "4F","double": "8F","decfloat": "8F","char": "A","varchar": "A","long varchar": "A","boolean": "A","binary": "H","varbinary": "H","VARBINARY": "H","date": "L","time": "T","timestamp": "Z","blob": "H","clob": "A","dbclob": "A","graphic": "G","vargraphic": "G","vargraphic": "G","long vargraphic": "G","long varchar for bit data": "H","varchar for bit data": "H","char for bit data": "H"}